update=Jeudi 22 mai 2014 15:31:25
last_client=cvpcb
[general]
version=1
[eeschema]
version=1
LibDir=
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=special
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=librairie KICAD/ad9954
LibName32=librairie KICAD/balun
LibName33=librairie KICAD/SMA_connectors
LibName34=librairie KICAD/inductor
LibName35=carteV1-cache
LibName36=librairie KICAD/oscillator-cmos-out-4
LibName37=librairie KICAD/MAX3421E-1-259960
LibName38=librairie KICAD/Power_kl
LibName39=librairie KICAD/FE
LibName40=librairie KICAD/mcp2210
LibName41=librairie KICAD/minicir
[pcbnew]
[pcbnew/libraries]
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=smd_capacitors
LibName7=smd_resistors
LibName8=smd_crystal&oscillator
LibName9=smd_dil
LibName10=smd_transistors
LibName11=libcms
LibName12=display
LibName13=led
LibName14=dip_sockets
LibName15=pga_sockets
LibName16=valves
LibName17=librairie KICAD/HC49_sm.kicad
LibName18=librairie KICAD/SOT223
LibName19=librairie KICAD/SMA_connectors
LibName20=librairie KICAD/OSC_SMD
LibName21=librairie KICAD/tinkerforge
LibName22=librairie KICAD/AD9954
LibName23=librairie KICAD/lasser
LibName24=Resistors_SMD
LibName25=librairie KICAD/smd_resistors
LibName26=librairie KICAD/open-project
LibName27=librairie KICAD/TANTALEC
LibDir=
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
